### ISSUE TITLE
Reran but couldn't get the same high Score on OntoNotes

### ISSUE THREAD

**Issue by FEEM-VAMPIRE** [xwhan/Extremely-Fine-Grained-Entity-Typing#5]
Hello XWHan, the work you contribute is gorgeous and I am sorry to disturb you, my problem is as follow:
I reran your model on the OntoNotes dataset, but couldn't perceive the result you proposed(which I can only get 65~67 ma_f1 and you submit 77.8 in your paper), I wonder if there is any trick or dataset preprocess I need to do before I rerun?

**Comment by xwhan** [comment]
As described in the paper, the ontonotes model is trained with augmented data. I have updated the training data path in ``config_parser.py``. Now you should be able to get similar results.

**Comment by FEEM-VAMPIRE** [comment]
Thanks so much! The result is totally ok now.
